quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      port: 5432
      volumes:
        "/tmp/db": /var/lib/postgresql/data
    jdbc: false
  hibernate-orm:
      database:
        generation: drop-and-create
