quarkus:
  datasource:
    jdbc: false
    db-kind: postgresql
    reactive:
  #    url: vertx-reactive:postgresql://localhost:5432/test
  hibernate-orm:
      database:
        generation: drop-and-create


#    devservices:
#      port: 5432
#    reactive:
#      url: vertx-reactive:postgresql://localhost:5432/mydatabase
#    url: postgresql://localhost:5432/quarkus_test