quarkus:
  datasource:
    db-kind: postgresql
#    devservices:
#      port: 5432
#      volumes:
#        "/tmp/db": /var/lib/postgresql/data
    jdbc: false
  hibernate-orm:
    log:
      sql: true
      format-sql: true
    database:
      generation: drop-and-create

